from typing import Protocol
from uuid import UUID

from app.domain.passport import PassportRead
from app.domain.schemas import AssessmentRead, PropertyRead


class PropertyRepository(Protocol):
    def save_property(self, item: PropertyRead) -> PropertyRead: ...
    def get_property(self, property_id: UUID) -> PropertyRead | None: ...
    def list_properties(self) -> list[PropertyRead]: ...


class AssessmentRepository(Protocol):
    def save_assessment(self, item: AssessmentRead) -> AssessmentRead: ...
    def latest_assessment(self, property_id: UUID) -> AssessmentRead | None: ...


class PassportRepository(Protocol):
    def save_passport(self, item: PassportRead) -> PassportRead: ...
    def get_passport(self, property_id: UUID) -> PassportRead | None: ...
